### ISSUE TITLE
not scaled right for 3440 x 1440 resolution

### ISSUE THREAD

**Issue by sharninator** [weiameili/Pensela#1]
app appears massive and oddly scaled on my 3440x1440 monitor - see picture 

![Screenshot (11)_LI](https://user-images.githubusercontent.com/59673029/119068307-46d83f00-ba27-11eb-8c96-02da113fd0f5.jpg)

**Comment by weiameili** [comment]
Just released a fix. Can you confirm that it works?

**Comment by sharninator** [comment]
wow there are so many tools i didnt realise how squished it was hahaha 

yes it looks better now, still quite large, but its displaying the entire tool bar. I can send you a picture tomorrow. Great job! I will keep having a play with this tool, could be really useful thanks

**Comment by weiameili** [comment]
You're Welcome
