### ISSUE TITLE
Pensela toolbar getting stuck under drawing board in i3

### ISSUE THREAD

**Issue by quasigod-io** [weiameili/Pensela#18]
I am using Pensela on i3. After setting it to float and excluding it from my blur effect in Picom, it works great visually. The problem is that when I draw on the drawing board, it focuses it and places it above the Pensela toolbar and I can no longer click on it. It's still usable for me, as I can place the toolbar on my second monitor so that the drawing board can't be above it. It seems as though this could be fixed relatively easily by adding a setting to make Pensela stay on top at all times.
![image](https://user-images.githubusercontent.com/62124625/137566661-0f9116f0-1826-4d24-a64a-846ebdb4c2be.png)
It's hard to show this in an image, but during this screenshot my mouse was over the toolbar and I had tried clicking on it (you can't see it because I took the image with flameshot), yet at the top left you can see the drawing board is still the focused window.

**Comment by weiameili** [comment]
Hi. Unfortunately, I tried multiple solutions for this but to no avail. However, it is still possible that this could be solved by changing the i3 config, which I do not know much about. What Pensela currently does is that it opens the Panel WIndow (with all the tools) as a child of the Drawing Board Window (Canvas). Can you configure i3 in a way that it always shows child windows on top of their parent?

**Comment by quasigod-io** [comment]
That's a good question. I know there is no way to make a specific window always on top in i3, but there may be a way to force the child window to stay on top. Something else I was thinking is that another possible workaround would be adding a way to configure the size of the window to allow the bar to sit above the drawing board. I'm going to try compiling it for myself with the window size changed. To see how well it works.
