### ISSUE TITLE
Screenshot in README

### ISSUE THREAD

**Issue by deadcoder0904** [weiameili/Pensela#2]
Would love to see some screenshots in the README :)

**Comment by weiameili** [comment]
I'll add the Screenshots and make a video when I get the time.

**Comment by weiameili** [comment]
Added a screenshot in the README. Doesn't really demonstrate a use case, but it should do for now.

**Comment by deadcoder0904** [comment]
Looks nice 👌

![screenshot](https://raw.githubusercontent.com/weiameili/Pensela/master/assets/screenshot.png)
