### ISSUE TITLE
[Bug]: Pensela Window becomes unclickable

### ISSUE THREAD

**Issue by ntolazzi** [weiameili/Pensela#22]
### What happened?

When I start Pensela and I choose any tool, I can not leave drawing mode anymore. The whole Pensela window becomes unresponsive as such, that I can draw onto the Pensela window but I cannot switch tools anymore and I cannot click on anything.

This also means I cannot stop the program without killing it via the console.

I use version 1.2.4-1 installed via the AUR in Archlinux. 

Btw version 1.2.4 is not choose-able in the issue creator.

### What did you expect to happen?

That I can still control Pensela to switch tools and to stop the program

### Pensela's version

Compiled from source

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by weiameili** [comment]
Hi, Which DE / WM are you using?

Also, just added v1.2.4 in the template :)

**Comment by ntolazzi** [comment]
Thanks for answering so fast :)

**Here is my system info:**

Operating System: Manjaro Linux
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.87.0
Qt Version: 5.15.2
Kernel Version: 5.15.2-2-MANJARO (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600G with Radeon Graphics
Memory: 30,8 GiB of RAM
Graphics Processor: AMD RENOIR

**Comment by weiameili** [comment]
And could you possibly be using multiple displays?

**Comment by ntolazzi** [comment]
Yes, that's true. I am using two displays.

**Comment by weiameili** [comment]
> Is there anything we could do to make it work with two displays connected

It should ideally work with multiple displays. I probably messed something up while adding support for multiple monitors. While it doesn't take long too find out the cause and patch it, I'm actually thinking about slightly changing how pensela works (Which will solve this and a couple of other issues) which might take slightly longer, but this should be fixed in the next release

**Comment by weiameili** [comment]
Should be fixed with v1.2.5. Can you confirm if it's works?

**Comment by ntolazzi** [comment]
I can confirm! It works. Thank you for the fast fix.
