### ISSUE TITLE
Suggestions to add

### ISSUE THREAD

**Issue by im-coder-lg** [weiameili/Pensela#9]
Hi! This is a cool project and I'd like to help here. I just want to know if you need these:

- [x] Issue Templates(Bug, Feature Requests, etc)
- [ ] Checks(for PRs so that you can know where the code is failing)
- [x] Contributing guide
- [ ] Code of Conduct (Contributor Code of Covenant or something similar)
- [x] License

I am making these as we speak. If you want, I can open a PR here. By the way, a question if you accept: What kind of license should I keep? There are a lot of them but I think the MIT License is best since it is widely used amongst GitHub projects.
Another question is: Does this project have social handles or Discord/Revolt servers? I could try linking them so that when people open issues, they can also visit them to see the process, or if you go to Settings and enable Discussions, I can add a link so that people can ask questions there while keeping the issue tracker(the Issues page) clean.

**Comment by weiameili** [comment]
Hi, thanks for looking into this. Firstly regarding the items you listed:
- Issue Templates and Checks would be really useful
- I already added a (pretty vague and general) contribution guideline in the README and also mentioned that this project is distributed under the ISC License (practically identical to the MIT License)
- Regarding the contributor Code of Conduct, there aren't that many people contributing to the project right now, I'll look into that when/if more people start contributing

> Does this project have social handles or Discord/Revolt servers?

Right now, this isn't that big a thing, to really require these. Although I will enable Discussions.

Thanks :)

**Comment by im-coder-lg** [comment]
> Issue Templates and Checks would be really useful

The checks are failing due to some error, I will look into it. If you also want to look into it, you can look here: [![nodejs-ci](https://github.com/im-coder-lg/Pensela/actions/workflows/ci.yml/badge.svg)](https://github.com/im-coder-lg/Pensela/actions/workflows/ci.yml)

That is a linking SVG, if you click it, you will see the steps I added there. Moreover, I will have to rename it so that's on my checklist for now.

**Comment by im-coder-lg** [comment]
And yeah, can you try posting the content of the ISC License you said? If I add it onto the License file, it will be displayed on GitHub.

**Comment by im-coder-lg** [comment]
Good! Now, I am making a checklist _here_ that will be updated regularly.
***
- [ ] Add Issue Templates(forms) with config(for adding the links, etc.) in YAML format.
- [ ] Fix the CI error(checks file is called CI)
- [ ] Add Discussion link to config for users.
- [ ] Add more things in the PR template.
- [ ] Get the PR up!
***
All of them are in the WIP stage, but I will test them and report back here. PS: Don't add any GitHub actions for automation, they might disturb the issue templates. I am choosing issue forms since issue templates can be easily manipulated, you can see everything on my fork.

**Comment by im-coder-lg** [comment]
Sorry @weiameili I have to delay because I am not getting enough time so I will have to do one feature in a day or something like that... Sorry for the delay, but I will try doing the issue forms tomorrow.

**Comment by im-coder-lg** [comment]
@weiameili The build has issues that I can't solve, so can you look into it? One of the problems is the `fs/promises` module needed.

**Comment by im-coder-lg** [comment]
So, for now, the CI is on hold. Once I figure out a solution for the error, I will add the CI.

**Comment by im-coder-lg** [comment]
I made the PR and added the CI, but it won't work yet. Once the build error is resolved, you can uncomment the CI and commit it.

**Comment by weiameili** [comment]
> @weiameili The build has issues that I can't solve, so can you look into it? One of the problems is the `fs/promises` module is needed. Maybe, in one of the JavaScript files, you might have added `import * from 'fs'` that made npm add more unstable packages.

It seems electron-builder requires `fs/promises`, which is available from nodejs 14+, and I take it the CI tries to build it with node 12.x too (where you will have to use `require("fs").promises` or some other equivalent). So just use node versions 14.x and 16.x in the CI then?.

**Comment by im-coder-lg** [comment]
Lemme try that

**Comment by weiameili** [comment]
Another problem with the checks is that the command being run, `npm run build`, builds the app for windows and Linux. Since the command is being run on all of the three platforms, there are a few problems:
- You need wine/docker to build windows apps on Linux, and docker for cross-platform builds on windows and mac os too (and none of these are available in the environments used in the checks)
- We're building for multiple targets on each of the three platforms, which isn't really necessary
- The command to build for mac os is different, so the CI is checking if you can build an exe and Linux package on macOS, but not dmg, which is what really matters

So I guess we should use separate commands for building the app for each target?

**Comment by im-coder-lg** [comment]
Hmmm... Maybe I will have to do some Action Syntax sleuthing... I will do it tomorrow

**Comment by im-coder-lg** [comment]
Everything seems to work thanks to the edit you made!
